#
#         Config file for J & J File editor
#    Developed by James Satherley & James Gorman
#
#
# All colours must be defined RGB values (0, 0, 0 would be black for example, max numbers are (255, 255, 255). These numbers are seperated into 3 3
# digit numbers (000,000,000) but must be put together. !!! If items error the file will be reset as a fail-safe !!!
#

# Blinking bar in document
Carot-Colour = 255,255,255

# When you click, hold and drag over text
Text-Highlight = 0, 56, 143

# Background colour of whole document
Background = 0, 21, 54

# Text Colour
Foreground = 214, 214, 214

# Line highlight colour
Line-Colour = 0, 36, 92

# Line number background colour
Gutter-Background = 0, 36, 92

# Line number text colour
Gutter-Foreground = 50, 214, 214

# Default window size (formatted w,h)
Window-Size = 1000, 800

# Font Name
Font = Dialog

# Font Style
Font-Style = 0

# Font Size
Font-Size = 12